apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  replicas: 4
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.34.1
        args:
        - query
        - --query.replica-label=prometheus_replica
        - --query.replica-label=receiver
        - --endpoint=thanos-store.default.svc:10901
        - --endpoint=thanos-ingesting-receiver.default.svc:10901
        - --query.tenant-header="THANOS-TENANT"
        - --query.enforce-tenancy
        - --query.auto-downsampling
        - |
          --tracing.config=type: JAEGER
          config:
            service_name: "thanos-querier"
            sampler_type: const
            sampler_param: 1
            endpoint: "http://jaeger.default.svc:14268/api/traces"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  selector:
    app: thanos-query
  ports:
  - name: http
    port: 9090
    targetPort: 10902