apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query-frontend
  template:
    metadata:
      labels:
        app: thanos-query-frontend
    spec:
      containers:
      - name: thanos-query-frontend
        image: quay.io/thanos/thanos:v0.34.1
        args:
        - query-frontend
        - --http-address=0.0.0.0:10902
        - --query-frontend.downstream-url=http://thanos-query.default.svc:9090
        - --query-range.split-interval=24h # default split interval
        - --query-range.request-downsampled
        ports:
        - name: http
          containerPort: 10902
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend
  labels:
    app: thanos-query-frontend
spec:
  selector:
    app: thanos-query-frontend
  ports:
  - name: http
    port: 10902
    targetPort: http
  type: ClusterIP